### ISSUE TITLE
[버그] 스프린트 참여는 되지만 참석자 목록에 표시되지 않습니다.

### ISSUE THREAD

**Issue by corazzon** [pythonkr/pyconkr-2018#118]
스프린트 참여는 되지만 참석자 목록이 표시되지 않습니다.

**Comment by iz4blue** [comment]
이게 유져 프로필이 없는 경우 문제가 되는 상황이였는데, 우선 오늘 퇴근하면 좀더 자세히 보도록 하겠습니다.

**Comment by corazzon** [comment]
@iz4blue 감사합니다 :)

**Comment by iiogmgo** [comment]
https://github.com/pythonkr/pyconkr-2018/pull/120
