### ISSUE TITLE
[등록프로세스] Registration 과 Profile 의 모호성

### ISSUE THREAD

**Issue by iiogmgo** [pythonkr/pyconkr-2018#2]
- 기본적으로 Registration 시 입력하는 이름 및 이메일 주소는 수정 불가능 하게 한다.
- Profile 의 이름은 Registration의 이름을 따라가고 이것도 수정 불가능하게 한다. (optional 로 영어이름을 추가로 받을 수 있게 할 수도 있을 것 같음) 
- 시스템 적으로는 Profile 이름 수정이 불가, 필요한 경우 별도 문의 하도록

(2017의 경우 profile, registration 의 정보가 달라 결제내역/영수증 에서의 이름이 다른 등의 이슈가 있었음)

**Comment by iiogmgo** [comment]
2018.03.23 논의를 통해 아래의 내용대로 수정

구매자 != 참가자 인 경우가 있을 수 있다.

registration - 구매자를 위한 정보 (영수증 등의 구매 이슈에서만 사용)
profile - 참가자를 위한 정보 (참가자 정보(티켓 이름은 해당 정보로 사용됨), 발표자 정보 등에서 사용)

각 정보를 사용처에 맞게 수정할 것 (영수증에서 profile 이름이 보이지 않도록 할 것 등등)

**Comment by makeajourney** [comment]
제 생각에는 registration이 참가자를 위한 정보가 되고, profile은 계정의 정보가 되는게 맞지 않을까 싶습니다. 티켓 양도시에도 registration상의 이름과 이메일을 변경하도록 하는게 좋지 않을까요?

**Comment by NohSeho** [comment]
@iiogmgo 님, 위에 '결제내역/영수증에서의 이름이 다른 등의 이슈'가 https://github.com/pythonkr/pyconkr-2017/issues/74 이슈 맞나요?

**Comment by iiogmgo** [comment]
@NohSeho 맞는 것 같습니다 :)

**Comment by iiogmgo** [comment]
@makeajourney 님의 의견과 관련하여 슬랙에서 논의해보고자 합니다-

**Comment by makeajourney** [comment]
@iiogmgo 개발 관련 이슈는 여기서 얘기하는 게 더 좋을 것 같아요.
