### ISSUE TITLE
[등록프로세스] 국내/해외 결제용 아임포트 설정값 분리

### ISSUE THREAD

**Issue by NohSeho** [pythonkr/pyconkr-2018#23]
보안상 구글드라이브 링크로 대체합니다.
본 이슈에 대한 내용은 파이콘 한국 준비위원회만 조회할 수 있습니다.

https://docs.google.com/document/d/1tK_5S3gAoqBtkTeACxrwVA8d4ig-M5tqECXBqgfJhvg/edit#heading=h.ingkm9hfyvve

**Comment by NohSeho** [comment]
개인후원 오픈 전에 이 이슈가 제일 먼저 작업되어야 할 것 같습니다.
위 구글 드라이브 링크에 있는 계정들로 테스트해보니까 수정되어야 할 부분이 있는 것 같은데,

상세 내용은 구글 드라이브에서 논의하는 것으로 하겠습니다.

**Comment by iiogmgo** [comment]
클-로즈하겠습니다
