### ISSUE TITLE
[등록프로세스] Option 모델 수정

### ISSUE THREAD

**Issue by iiogmgo** [pythonkr/pyconkr-2018#3]
- Constance 에 있는 등록 가능 일자 및 총 티켓수 관련 config 제거
- Option 마다 등록가능 시작일시 / 종료일시, 티켓 수를 명시적으로 지정
- 홈페이지에 노출해야 할 Option 필드 따로 정의

**Comment by makeajourney** [comment]
총 티켓 수 관련 config 제거는 안되었는데 이거 제거해야 하나요??

**Comment by kucuny** [comment]
일단 이 코드는 머지되었기 때문에 closed 합니다.

**Comment by makeajourney** [comment]
@kucuny 제가 보기에 총 티켓수 관련 config는 등록된 option 전체의 티켓 수가 우리 예상 인원 규모를 벗어나지 않게 하기 위해 있는게 아닌가 싶은데, option모델에는 어느 한 option에 대한 수량만 지정하는 것 아닌가요?

**Comment by kucuny** [comment]
@makeajourney 맞습니다. 실제 등록시에도 해당 `Option.total`을 기준으로 validation 하면 됩니다.
`constance`의 총 티켓 수는 이런 의미에서 필요하지 않다고 생각합니다.
