### ISSUE TITLE
등록 확인시 티켓 이름에 2017년 표기가 남아있습니다.

### ISSUE THREAD

**Issue by lqez** [pythonkr/pyconkr-2018#42]
<img width="626" alt="screen shot 2018-06-01 at 4 32 34 pm" src="https://user-images.githubusercontent.com/579366/40827721-6c5b1ede-65b9-11e8-906b-a48aaf51d04a.png">
티켓 이름에 2017년 표기가 남아있습니다.

**Comment by NohSeho** [comment]
제보 감사합니다!
https://github.com/pythonkr/pyconkr-2018/pull/43 에서 처리됐습니다.
확인 부탁드립니다 :)

**Comment by lqez** [comment]
감사합니다.
