### ISSUE TITLE
후원사 목록 노출 

### ISSUE THREAD

**Issue by iiogmgo** [pythonkr/pyconkr-2018#44]
1. 후원사 목록 단독 페이지
2. pycon.kr 메인페이지 맨 밑에 후원사 목록 보이게

**Comment by makeajourney** [comment]
이 부분은 티저에 붙이는 작업 진행하지 않고 공식홈페이지 오픈으로 대체합니다.

**Comment by NohSeho** [comment]
후원사 목록은 노출되고 있는데, 이미지가 너무 크게 나오는걸 보니 이미지 사이즈랑 solr 썸네일이 적용 안 된 것 같네요.
이미지 사이즈를 지금보다 작게 적용하고 solr 썸네일 적용 시켜서 이미지 용량을 줄이면 좋을 것 같아요.

**Comment by makeajourney** [comment]
해주세요 @NohSeho
