### ISSUE TITLE
[등록프로세스] 환불

### ISSUE THREAD

**Issue by iiogmgo** [pythonkr/pyconkr-2018#5]
- 가상계좌 : 티켓 구매시 환불받을 계좌번호 및 예금주를 받도록
- (필수는 아닐듯) 단체 티켓의 경우 : 부분취소 가능해야 함(10명 중 2명만 취소한다던가...)

**Comment by iiogmgo** [comment]
환불 관련은 https://github.com/pythonkr/pyconkr-2017/issues/102 해당 이슈와도 맞물려 진행되면 좋을 듯

**Comment by NohSeho** [comment]
가상 계좌 환불 실패에 관한 케이스도 고려해두면 추후에 매뉴얼을 작성할 때 도움이 될 것 같습니다.
(환불받을 계좌번호와 예금주가 오타, 존재하지 않는 계좌번호 등으로 인한 실패의 경우 등)

**Comment by iiogmgo** [comment]
@NohSeho 가장 좋은 방법은 예금주, 계좌 가 존재하는지 validate 검사를 해두면 가장 좋은데, 어렵다면 이메일로 통보해드리는 방식으로 우회하게 될 것 같습니다.

**Comment by kucuny** [comment]
@iiogmgo 예금주, 계좌가 존재하는지 저희가 알 수 있는 빙법은 없을겁니다. 대신 입력빋는 예금주를 최초 등록했을 때 입력했던 이름정도로 validation 하면 어떨지요? 그 전에 등록/취소 히스토리 모델링을 먼저 해야할 듯 합니다. 제가 작업하도록 하지요.

**Comment by iiogmgo** [comment]
올해까지 수동으로 진행합니다. 닫습니다.
