### ISSUE TITLE
쉬는 시간 네이밍

### ISSUE THREAD

**Issue by BetaF1sh** [pythonkr/pyconkr-2018#95]
안녕하세요. [오늘 공개된 세부일정](https://www.pycon.kr/2018/program/schedule/)에서 의문이 들어 이슈 올려봅니다.

굳이 쉬는시간 제목을 `XX:XX분에서 시작하는 XX분 쉬는시간` 으로 하신 이유에 궁금하네요. 아직 작업이 덜 끝난 부분인가요?

**Comment by ppiyakk2** [comment]
안녕하세요. 올해에는 쉬는 시간을 재미있게 표현해보았습니다. 작업이 덜 끝난 것은 아닙니다. ^^
